apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-devops-app
spec:
  replicas: 1  # Matches your worker nodes
  #Add deployment strategy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: spring-devops-app
  template:
    metadata:
      labels:
        app: spring-devops-app
    spec:
      #Added termination grace period
      terminationGracePeriodSeconds: 30
      containers:
        - name: spring-devops-app
          image: mzishan007/devops-integration:latest
          ports:
            - containerPort: 8081  # Update if your app uses a different port
            # Add lifecycle hooks
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
      imagePullSecrets:
        - name: dockerhub-secret  # Add this section

