apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-pipline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-cd-pipline
  template:
    metadata:
      labels:
        app: ci-cd-pipline
    spec:
      containers:
        - name: ci-cd-pipline
          image: mzishan007/devops-integration:latest  # Will be replaced
          ports:
            - containerPort: 8081